Build
=============

Step 1.) Install I2CMaster Library

cd /folder/to/build/I2CMaster
git clone https://github.com/bstrysko/I2CMaster
cd I2CMaster/
make
sudo make install

You can delete the folders you created if you wish after sucessfully
running sudo make install .


Step 2.) Compile and Run Project

make
sudo ./main
